(function() {var implementors = {
"oxc_parser":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"oxc_parser/enum.Kind.html\" title=\"enum oxc_parser::Kind\">Kind</a>"]],
"ssc_ast":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"ssc_ast/ast/enum.Namespace.html\" title=\"enum ssc_ast::ast::Namespace\">Namespace</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"ssc_ast/enum.AstType.html\" title=\"enum ssc_ast::AstType\">AstType</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"ssc_ast/struct.Comment.html\" title=\"struct ssc_ast::Comment\">Comment</a>"],["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"ssc_ast/enum.AstKind.html\" title=\"enum ssc_ast::AstKind\">AstKind</a>&lt;'a&gt;"]],
"ssc_codegen":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"ssc_codegen/struct.CodegenOptions.html\" title=\"struct ssc_codegen::CodegenOptions\">CodegenOptions</a>"]],
"ssc_css_ast":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"ssc_css_ast/enum.AstType.html\" title=\"enum ssc_css_ast::AstType\">AstType</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"ssc_css_ast/struct.Comment.html\" title=\"struct ssc_css_ast::Comment\">Comment</a>"],["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"ssc_css_ast/enum.AstKind.html\" title=\"enum ssc_css_ast::AstKind\">AstKind</a>&lt;'a&gt;"]],
"ssc_css_codegen":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"ssc_css_codegen/struct.CodegenOptions.html\" title=\"struct ssc_css_codegen::CodegenOptions\">CodegenOptions</a>"]],
"ssc_css_parser":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"ssc_css_parser/enum.Kind.html\" title=\"enum ssc_css_parser::Kind\">Kind</a>"]],
"ssc_parser":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"ssc_parser/enum.Kind.html\" title=\"enum ssc_parser::Kind\">Kind</a>"]],
"ssc_wasm":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"ssc_wasm/struct.Comment.html\" title=\"struct ssc_wasm::Comment\">Comment</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"ssc_wasm/struct.Diagnostic.html\" title=\"struct ssc_wasm::Diagnostic\">Diagnostic</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()