[workspace]
members  = ["crates/*"]
resolver = "2"


  [workspace.package]
  authors      = ["Dilshad <a-rustacean@outlook.com>"]
  categories   = ["development-tools", "web-programming", "compilers"]
  description  = "The Svelte compiler, rewritten in Rust."
  edition      = "2021"
  homepage     = "https://github.com/a-rustacean/svelte-oxide#readme"
  keywords     = ["svelte", "compiler"]
  license      = "MIT"
  readme       = "README.md"
  repository   = "https://github.com/a-rustacean/svelte-oxide"
  rust-version = "1.74"

  [workspace.dependencies]
  assert-unchecked  = "0.1.2"
  bitflags          = "2.5.0"
  lazy_static       = "1.4.0"
  memchr            = "2.7.2"
  num-bigint        = "0.4.5"
  phf               = { version = "0.11.2", features = ["macros"] }
  regex             = "1.10.4"
  rustc-hash        = "1.1.0"
  seq-macro         = "0.3.5"
  static_assertions = "1.1.0"

  # Oxc
  oxc_allocator   = "0.12.5"
  oxc_ast         = "0.12.5"
  oxc_diagnostics = "0.12.5"
  oxc_index       = "0.12.5"
  oxc_parser      = { path = "crates/oxc_parser" }
  oxc_semantic    = "0.12.5"
  oxc_sourcemap   = "0.12.5"
  oxc_span        = "0.12.5"
  oxc_syntax      = "0.12.5"

  # Svelte Oxide
  svelte_oxide          = { path = "crates/svelte_oxide" }
  svelte_oxide_analyzer = { path = "crates/svelte_oxide_analyzer" }
  svelte_oxide_ast      = { path = "crates/svelte_oxide_ast" }
  svelte_oxide_parser   = { path = "crates/svelte_oxide_parser" }
