name: Docs

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

jobs:
  rustdoc:
    name: Rustdoc
    runs-on: macos-latest

    steps:
      - uses: taiki-e/checkout-action@v1

      - name: Install Rust Toolchain
        uses: ./.github/actions/rustup
        with:
          nightly: true
          docs: true

      - name: Create rustdoc
        run: cargo +nightly doc --all --no-deps -Zunstable-options -Zrustdoc-scrape-examples

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: target/doc
          clean: true
          git-config-email: a-rustacean@outlook.com
          commit-message: "Update documentation"
          single-commit: true
